### ISSUE TITLE
conditionalPanel produces error in browser and has erratic behaviour

### ISSUE THREAD

**Issue by rmbielby** [dfe-analytical-services/education-to-employment-dashboard#24]
The conditionalPanel() function seems to lead to erratic behaviour in the browser. We saw significant performance issues in the LEO dashboard that seemed to relate to conditionalPanel() as well as the conditionalPanel() just not behaving as required. The same issues aren't necessarily seen in the Education to Employment Dashboard as yet, but we do see the following error in the browser console:

> Uncaught TypeError: Cannot read properties of undefined (reading 'style')
>     at Ha (<anonymous>:69:413)
>     at ta (<anonymous>:29:440)
>     at Pa (<anonymous>:63:64)
>     at Qb (<anonymous>:53:310)
>     at <anonymous>:50:337
>     at Object.g [as success] (<anonymous>:49:73)
>     at c (jquery.min.js:2:28327)
>     at Object.fireWith [as resolveWith] (jquery.min.js:2:29072)
>     at l (jquery.min.js:2:79901)
>     at XMLHttpRequest.<anonymous> (jquery.min.js:2:82355)
> 

Safest course of action would seem to be to remove this conditionalPanel() and replace with a simple bit of code to render the conditional elements using observeEvent(). Main goal would just be to not have the error coming up in the browser console, whilst maintaining the desired functionality.

**Comment by rmbielby** [comment]
Sidestepped in #27
